// images 200x200

export default [
    {
        id: 0,
        name: 'StartSe',
        url: 'https://www.startse.com/',
        image: 'signacast.jpg',
    },
    {
        id: 1,
        name: 'Bionote',
        url: 'https://itunes.apple.com/br/podcast/bionote/id1339439741?mt=2',
        image: 'bionote.jpg',
    },
    {
        id: 2,
        name: 'Brasil Junior',
        url: 'https://soundcloud.com/brasil-junior',
        image: 'bjcast.jpg',
    },
    {
        id: 3,
        name: 'Coffea',
        url: 'http://portalcoffea.com/',
        image: 'coffea.jpg',
    },
    {
        id: 4,
        name: 'Data Hackers',
        url: 'http://datahackers.com.br/',
        image: 'datahackers.jpg',
    },
    {
        id: 5,
        name: 'DevNaEstrada',
        url: 'http://devnaestrada.com.br/',
        image: 'devnaestrada.jpg',
    },
    {
        id: 6,
        name: 'Fotologia',
        url: 'https://www.fotologia.net/',
        image: 'fotologia.jpg',
    },
    {
        id: 7,
        name: 'Futurice',
        url: 'http://www.futurecocreated.com/',
        image: 'futurice.jpg',
    },
    {
        id: 8,
        name: 'Garter Brasil',
        url: 'https://www.gartner.com',
        image: 'gartner.jpg',
    },
    {
        id: 9,
        name: 'LabFazedores',
        url: 'http://kaioserrate.com/?s=podcast',
        image: 'labfazedores.jpg',
    },
    {
        id: 10,
        name: 'Meteora Podcast',
        url: 'https://soundcloud.com/meteora-podcast',
        image: 'meteora.jpg',
    },
    {
        id: 11,
        name: 'PodTag',
        url: 'https://podtag.com.br/',
        image: 'podtag.jpg',
    },
    {
        id: 12,
        name: 'Poker Pro Brasil',
        url: 'https://www.pokerprobrasil.com.br/',
        image: 'pokerpro.jpg',
    },
    {
        id: 13,
        name: 'Papricast',
        url: 'http://paprica.org/',
        image: 'papricast.jpg',
    },
    {
        id: 14,
        name: 'Supera',
        url: 'http://www.superafarma.com.br/',
        image: 'superafarma.jpg',
    },
    {
        id: 15,
        name: 'Clinical Papers Podcast',
        url: 'http://www.clinicalpaperspodcast.com.br/podcasts/',
        image: 'superafarma.jpg',
    },
    {
        id: 16,
        name: 'E-DublinCast',
        url: 'https://www.e-dublin.com.br/tag/e-dublincast/',
        image: 'superafarma.jpg',
    },
    {
        id: 17,
        name: 'ElaPod - Fernanda Ponzeto',
        url: 'https://open.spotify.com/episode/5Dk15WT3hH1Z4jaWZNU03W',
        image: 'superafarma.jpg',
    },
    {
        id: 18,
        name: 'Revista HSM - Podcast eXtraCast',
        url: 'https://www.revistahsm.com.br/',
        image: 'superafarma.jpg',
    },
    {
        id: 19,
        name: 'InfieldCast',
        url: 'http://infieldcast.com.br/',
        image: 'superafarma.jpg',
    },
    {
        id: 20,
        name: 'PapoAgro Podcast',
        url: 'https://open.spotify.com/show/4d8r1zgRllGYmwJ0wnTSvM',
        image: 'superafarma.jpg',
    },
    {
        id: 21,
        name: 'Podcasts Mzero',
        url: 'https://mzero.net.br/',
        image: 'superafarma.jpg',
    },
    {
        id: 22,
        name: 'Geekonimics',
        url: 'https://geekonomics.com.br/category/podcast/',
        image: 'superafarma.jpg',
    },
];
